#.travis.yml

language: node_js

branches:
  only:
    - master
    - /^greenkeeper/.*$/

before_script:
  - npm install -g firebase-tools
  - npm install -g angular-cli

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
